### ISSUE TITLE
Will you add support for ASP.NET 5 + MVC 6?

### ISSUE THREAD

**Issue by glen-84** [troygoode/PagedList#108]

**Comment by glen-84** [comment]
@troygoode

I've done the conversion and I'm trying to decide whether to fork this repo or create a new one, and what version numbers to use. What would you suggest?

**Comment by troygoode** [comment]
@glen-84 I haven't worked in Windows/.NET for years so I'm unlikely to make any further changes

**Comment by glen-84** [comment]
@troygoode Okay, I will fork or create a new repo (not yet sure which). Thanks.

**Comment by migig** [comment]
@troygoode Well then could you state that in bold on the homepage, so the rest of us know that this nuget package is unsupported? I made a PR which I now know won't ever be used. Thanks for this package it was truly great while it lasted, but do the decent thing and let others know to avoid it and choose something else.
